import streamlit as st

st.set_page_config(
    page_title="Agri-Price Intelligence",
    page_icon="🌽",
)

st.write("# Welcome to Agri-Price Intelligence!")

st.markdown(
    """
    This platform provides real-time monitoring of agricultural commodity prices across the Philippines.
    
    ### Select a Module from the sidebar to begin.
    
    **Available Modules:**
    - **National Market Watch**: Comprehensive dashboard for price monitoring, anomaly detection, and market analysis.
    - **Historical Trends**: Strategic view for analyzing long-term price trajectories and market volatility.
    
    ### System Status
    - **Data Pipeline**: Active (Daily Updates)
    - **Coverage**: 17 Regions
    - **Commodities**: Rice, Corn, Meat, Fish, Vegetables, Fruits
    """
)

st.markdown("---")

with st.expander("Platform Documentation & Terms of Use", expanded=False):
    st.markdown("""
    ### Data Attribution & Architecture
    All data is independently extracted from the official [Philippine Department of Agriculture (DA) Bantay Presyo](http://www.bantaypresyo.da.gov.ph/) platform via an automated ELT pipeline.

    ### Pipeline SLA (Data Freshness)
    **Data Update Schedule**: The extraction engine operates on a daily batch schedule. Prices reflect the end-of-day reports generated by the DA. This dashboard does not provide live, minute-by-minute market data.

    ### Standard Operating Procedure
    *   **National Market Watch**: Designed for tactical, daily market analysis. Select a specific administrative region and commodity category to identify the lowest prevailing market prices and detect regional price variations.
    *   **Historical Trends**: A strategic analysis tool. Filter by date ranges to identify volatility and supply chain pricing trajectories over time.

    ### Developer Signature
    Built as an automated Data Engineering portfolio project. To view the pipeline architecture or source code, please visit my GitHub profile:
    *   [GitHub Profile](https://github.com/crylz-z)

    ### Limitation of Liability
    This platform is provided for informational, educational, and portfolio demonstration purposes only. The data is aggregated from public government sources and is provided 'AS IS' without warranties of any kind, either express or implied, regarding accuracy, completeness, or real-time timeliness. The creator of this platform assumes no liability for any financial, trading, procurement, or business decisions made based on this data. Users must independently verify all prices and market conditions prior to conducting commercial transactions.
    """)
