import pandas as pd
import folium
from datetime import datetime

import streamlit as st
import sys
import os

# Ensure root is in path for imports
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../")))

from src.dashboard.utils import ui
from src.dashboard.utils.data_engine import DataEngine

ui.apply_enterprise_styling()

# ==========================================
# PAGE HEADER
# ==========================================
st.markdown(
    """
    <div style="text-align:center; margin-bottom:1rem;">
        <h1 style="font-size:2rem; font-weight:700; color:#1e3a5f; margin-bottom:0.1rem;">
            Agri-Price Intelligence Platform
        </h1>
        <p style="color:#6B7280; font-size:0.9rem; margin-top:0;">
            Real-time agricultural commodity price monitoring across the Philippines
        </p>
    </div>
    """,
    unsafe_allow_html=True,
)

# ==========================================
# SYSTEM STATUS — 3-column KPI grid
# ==========================================
st.markdown("#### System Status")
c1, c2, c3 = st.columns(3)
with c1:
    with st.container(border=True):
        st.metric("Coverage", "17 Regions", delta=None)
with c2:
    with st.container(border=True):
        st.metric("Pipeline", "Active", delta="Daily Updates", delta_color="normal")
with c3:
    with st.container(border=True):
        st.metric("Commodities", "6 Categories", delta=None)

st.markdown("<div style='margin-top:1rem;'></div>", unsafe_allow_html=True)

# ==========================================
# AVAILABLE MODULES — 2-column portal cards
# ==========================================
st.markdown("#### Available Modules")
m1, m2 = st.columns(2)

with m1:
    with st.container(border=True):
        st.markdown(
            """
            <h4 style="color:#1e3a5f; margin-bottom:0.25rem;">National Market Watch</h4>
            <p style="color:#6B7280; font-size:0.88rem; margin-top:0;">
                Tactical daily price monitoring — identify regional price variations,
                detect potential price gouging, and pinpoint the best-value markets
                for any commodity on any given date.
            </p>
            """,
            unsafe_allow_html=True,
        )

with m2:
    with st.container(border=True):
        st.markdown(
            """
            <h4 style="color:#1e3a5f; margin-bottom:0.25rem;">Historical Trends</h4>
            <p style="color:#6B7280; font-size:0.88rem; margin-top:0;">
                Strategic long-term analysis — track price trajectories over 7, 30,
                or 90-day windows, measure market volatility, and identify the
                historically cheapest day of the week to buy.
            </p>
            """,
            unsafe_allow_html=True,
        )

st.markdown("---")

# ==========================================
# PLATFORM DOCUMENTATION
# ==========================================
with st.expander("Platform Documentation & Terms of Use", expanded=False):
    st.markdown(
        """
    ### Data Attribution & Architecture
    All data is independently extracted from the official [Philippine Department of Agriculture (DA) Bantay Presyo](http://www.bantaypresyo.da.gov.ph/) platform via an automated ETL pipeline.

    ### Pipeline SLA (Data Freshness)
    **Data Update Schedule**: The extraction engine operates on a daily batch schedule. Prices reflect end-of-day reports generated by the DA. This dashboard does not provide live, minute-by-minute market data.

    ### Standard Operating Procedure
    *   **National Market Watch**: Designed for tactical, daily market analysis. Select a specific administrative region and commodity category to identify lowest prevailing market prices and detect regional price variations.
    *   **Historical Trends**: A strategic analysis tool. Filter by date ranges to identify volatility and supply chain pricing trajectories over time.

    ### Developer Signature
    Built as an automated Data Engineering portfolio project. To view the pipeline architecture or source code, please visit:
    *   [GitHub Profile](https://github.com/crylz-z)

    ### Limitation of Liability
    This platform is provided for informational, educational, and portfolio demonstration purposes only. The data is aggregated from public government sources and is provided 'AS IS' without warranties of any kind, either express or implied, regarding accuracy, completeness, or real-time timeliness. The creator of this platform assumes no liability for any financial, trading, procurement, or business decisions made based on this data. Users must independently verify all prices and market conditions prior to conducting commercial transactions.
    """
    )

st.caption(
    "Data Source: [Department of Agriculture - Bantay Presyo](http://www.bantaypresyo.da.gov.ph/) | © 2026 Agri-Price Intelligence Platform"
)


def main():
    st.title("📋 Official Market Bulletin")

    # ---------------------------
    # SIDEBAR: HIERARCHY
    # ---------------------------
    # The Global Date is now handled above pg.run() and stored in session state
    selected_date = st.session_state.get(
        "global_date", datetime.today().strftime("%Y-%m-%d")
    )

    # LOAD DATA (LKGV)
    raw_df = DataEngine.load_data_window(selected_date)

    if raw_df is None or raw_df.empty:
        st.error(
            f"System Offline: Unable to load data window from Silver layer for {selected_date}."
        )
        return

    # COALESCE (The "Squash" Operation)
    # 1. Sort by Date Descending (Newest first)
    raw_df = raw_df.sort_values("extract_dt", ascending=False)

    # 2. Dedup (Keep first/newest)
    # Natural Key: Region + Market + Commodity.
    df = raw_df.drop_duplicates(
        subset=["region_name", "market_name", "commodity"], keep="first"
    ).copy()

    # 3. Calculate Freshness
    target_dt = datetime.strptime(selected_date, "%Y-%m-%d")
    df["days_ago"] = (target_dt - df["extract_dt"]).dt.days
    df["days_ago"] = df["days_ago"].fillna(0).astype(int)

    # LEVEL 2: REGION (Global)
    if "region_name" not in df.columns:
        st.error("Data integrity error: 'region_name' column missing.")
        return

    valid_regions = sorted(df["region_name"].dropna().unique())
    selected_region = st.sidebar.selectbox("Region", valid_regions)

    # FILTER STEP 1
    region_df = df[df["region_name"] == selected_region].copy()

    # LEVEL 3: CATEGORY (Primary Filter)
    if "category" not in region_df.columns:
        st.error("Data integrity error: 'category' column missing.")
        return

    valid_categories = sorted(region_df["category"].dropna().unique())
    selected_category = st.sidebar.selectbox("Category", valid_categories)

    # FILTER STEP 2
    category_df = region_df[region_df["category"] == selected_category].copy()

    # LEVEL 4: COMMODITY (Secondary Filter for Drill-Down)
    if "commodity" not in category_df.columns:
        st.error("Data integrity error: 'commodity' column missing.")
        return

    valid_commodities = sorted(category_df["commodity"].dropna().unique())
    selected_commodity = st.sidebar.selectbox(
        "Deep Dive Commodity", valid_commodities, index=0
    )

    # FILTER STEP 3
    commodity_df = category_df[category_df["commodity"] == selected_commodity].copy()

    # LOAD REFERENCE
    geo_df, srp_df = DataEngine.load_reference_data()

    # ==========================================
    # ZONE A: EXECUTIVE BRIEF (Category Level)
    # ==========================================
    st.subheader(f"Executive Brief: {selected_category} in {selected_region}")

    # Category Stats
    avg_price = category_df["price"].mean()
    min_price = category_df["price"].min()
    max_price = category_df["price"].max()
    volatility = ((max_price - min_price) / avg_price) * 100 if avg_price > 0 else 0

    # Status Banner
    if volatility > 20:
        st.warning(
            f"⚠️ **High Volatility Detected**: Prices in this category vary by {volatility:.0f}%. Check for outliers."
        )
    elif volatility < 10:
        st.success(
            f"✅ **Stable Market**: Price variance is low ({volatility:.0f}%) across commodities."
        )
    else:
        st.info("ℹ️ **Moderate Activity**: Standard price fluctuations observed.")

    # KPI Cards
    k1, k2, k3 = st.columns(3)
    k1.metric("Markets Reporting", category_df["market_name"].nunique())
    k2.metric("Category Avg Price", f"₱{avg_price:,.2f}")
    k3.metric("Commodities Tracked", category_df["commodity"].nunique())

    st.markdown("---")

    # ==========================================
    # ZONE B: OFFICIAL PRICE BULLETIN (The Hero)
    # ==========================================
    st.subheader("📢 Official Price Bulletin")

    # Aggregate Live Data by Commodity
    # We aggregate Price (mean) and Days Ago (max - being conservative, showing staleness if any)
    bulletin_df = (
        category_df.groupby("commodity")
        .agg(
            {
                "price": "mean",
                "days_ago": "max",  # If one market is stale, we warn? Or 'min' (best case)?
                # Let's use 'max' (Worst Case) to be transparent.
            }
        )
        .reset_index()
    )

    bulletin_df.rename(columns={"price": "Live Avg"}, inplace=True)

    # Merge with SRP (Left Join to keep all live commodities)
    # Ensure join on commodity name
    bulletin_df = bulletin_df.merge(srp_df, on="commodity", how="left")

    # Logic
    def get_status(row):
        live = row["Live Avg"]
        srp = row["srp"]
        if pd.isna(srp):
            return "N/A"
        if live > (srp * 1.10):
            return "High 🔺"
        if live < (srp * 0.90):
            return "Low 📉"
        return "Fair ✅"

    bulletin_df["Status"] = bulletin_df.apply(get_status, axis=1)
    bulletin_df["Diff"] = bulletin_df["Live Avg"] - bulletin_df["srp"]

    # Formatting Helpers
    def format_currency(val):
        return f"₱{val:,.2f}" if pd.notnull(val) else "—"

    def format_diff(val):
        if pd.isna(val):
            return "—"
        return f"{val:+.2f}"

    def format_freshness(days):
        if days == 0:
            return "Today"
        if days == 1:
            return "Yesterday"
        return f"{days} Days Ago"

    bulletin_df["Data As Of"] = bulletin_df["days_ago"].apply(format_freshness)

    # Display Table
    st.dataframe(
        bulletin_df.style.apply(
            lambda x: ["background-color: #ffe6e6" if "High" in v else "" for v in x],
            subset=["Status"],
        )
        .apply(
            lambda x: [
                "color: #e67e22; font-weight: bold" if v > 0 else "color: #2ecc71"
                for v in x
            ],
            subset=["days_ago"],
        )
        .format(
            {"Live Avg": format_currency, "srp": format_currency, "Diff": format_diff}
        ),
        column_order=["commodity", "srp", "Live Avg", "Diff", "Status", "Data As Of"],
        column_config={
            "commodity": "Commodity",
            "srp": "Prevailing Price (SRP)",
            "Live Avg": "Current Avg Price",
            "Diff": "Variance",
            "Data As Of": "Freshness",
        },
        use_container_width=True,
        hide_index=True,
    )

    # ==========================================
    # DRILL DOWN SECTION
    # ==========================================
    st.markdown("---")
    st.header(f"🔍 Deep Dive: {selected_commodity}")

    if commodity_df.empty:
        st.warning(f"No live data for **{selected_commodity}** today.")
        return

    col_map, col_chart = st.columns([1, 1])

    # ==========================================
    # ZONE C: GEOSPATIAL MAP
    # ==========================================
    with col_map:
        st.subheader("📍 Market Location")

        # Merge Geo
        map_df = commodity_df.merge(geo_df, on="market_name", how="inner")

        if not map_df.empty:
            avg_comm_price = commodity_df["price"].mean()
            center_lat = map_df["lat"].mean()
            center_lon = map_df["lon"].mean()

            m = folium.Map(location=[center_lat, center_lon], zoom_start=11)

            for _, row in map_df.iterrows():
                price = row["price"]
                color = "green" if price <= avg_comm_price else "red"
                folium.CircleMarker(
                    location=[row["lat"], row["lon"]],
                    radius=8,
                    color=color,
                    fill=True,
                    fill_color=color,
                    tooltip=f"{row['market_name']}: ₱{price:,.2f}",
                ).add_to(m)

            import streamlit_folium

            streamlit_folium.st_folium(m, height=400, use_container_width=True)
            st.caption("Green: Below Regional Avg | Red: Above Regional Avg")
        else:
            st.info("Geographic data not available for these markets.")

    # ==========================================
    # ZONE D: ANALYTICS
    # ==========================================
    with col_chart:
        st.subheader("📊 Price Fairness")

        # Z-Score
        if commodity_df["price"].std() > 0:
            commodity_df["z_score"] = (
                commodity_df["price"] - commodity_df["price"].mean()
            ) / commodity_df["price"].std()
            commodity_df["color"] = commodity_df["z_score"].apply(
                lambda x: "#e74c3c" if x > 0 else "#2ecc71"
            )

            import plotly.express as px

            fig = px.bar(
                commodity_df,
                y="market_name",
                x="z_score",
                orientation="h",
                title="Fairness Meter (Z-Score)",
                text=commodity_df["price"].apply(lambda x: f"₱{x:.0f}"),
            )
            fig.update_traces(marker_color=commodity_df["color"])
            fig.add_vline(x=0, line_dash="dash", line_color="black")
            st.plotly_chart(fig, use_container_width=True)
            st.caption("How to read: Bars to the RIGHT are expensive markets.")
        else:
            st.info("Price is uniform across all markets (No Variance).")

    # Box Plot Row
    st.subheader("📈 Price Distribution")
    import plotly.express as px

    fig_box = px.box(
        commodity_df,
        x="price",
        points="all",
        height=200,
        title=f"Price Range for {selected_commodity}",
    )
    st.plotly_chart(fig_box, use_container_width=True)
    st.caption(
        "How to read: Dots outside the box are outliers (potential price gouging)."
    )


main()
