import pandas as pd
from datetime import datetime

import streamlit as st
import sys
import os

# Ensure root is in path for imports
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../")))

from src.dashboard.utils import ui
from src.dashboard.utils.data_engine import DataEngine

ui.apply_enterprise_styling()

# ==========================================
# PAGE HEADER
# ==========================================
st.markdown(
    """
    <div style="text-align:center; margin-bottom:1rem;">
        <h1 style="font-size:2rem; font-weight:700; color:#1e3a5f; margin-bottom:0.1rem;">
            Agri-Price Intelligence Platform
        </h1>
        <p style="color:#6B7280; font-size:0.9rem; margin-top:0;">
            Real-time agricultural commodity price monitoring across the Philippines
        </p>
    </div>
    """,
    unsafe_allow_html=True,
)

# ==========================================
# SYSTEM STATUS — 3-column KPI grid
# ==========================================
st.markdown("#### System Status")
c1, c2, c3 = st.columns(3)
with c1:
    with st.container(border=True):
        st.metric("Coverage", "17 Regions", delta=None)
with c2:
    with st.container(border=True):
        st.metric("Pipeline", "Active", delta="Daily Updates", delta_color="normal")
with c3:
    with st.container(border=True):
        st.metric("Commodities", "6 Categories", delta=None)

st.markdown("<div style='margin-top:1rem;'></div>", unsafe_allow_html=True)

# ==========================================
# AVAILABLE MODULES — 2-column portal cards
# ==========================================
st.markdown("#### Available Modules")
m1, m2 = st.columns(2)

with m1:
    with st.container(border=True):
        st.markdown(
            """
            <h4 style="color:#1e3a5f; margin-bottom:0.25rem;">National Market Watch</h4>
            <p style="color:#6B7280; font-size:0.88rem; margin-top:0;">
                Tactical daily price monitoring — identify regional price variations,
                detect potential price gouging, and pinpoint the best-value markets
                for any commodity on any given date.
            </p>
            """,
            unsafe_allow_html=True,
        )

with m2:
    with st.container(border=True):
        st.markdown(
            """
            <h4 style="color:#1e3a5f; margin-bottom:0.25rem;">Historical Trends</h4>
            <p style="color:#6B7280; font-size:0.88rem; margin-top:0;">
                Strategic long-term analysis — track price trajectories over 7, 30,
                or 90-day windows, measure market volatility, and identify the
                historically cheapest day of the week to buy.
            </p>
            """,
            unsafe_allow_html=True,
        )

st.markdown("---")

# ==========================================
# PLATFORM DOCUMENTATION
# ==========================================
with st.expander("Platform Documentation & Terms of Use", expanded=False):
    st.markdown(
        """
    ### Data Attribution & Architecture
    All data is independently extracted from the official [Philippine Department of Agriculture (DA) Bantay Presyo](http://www.bantaypresyo.da.gov.ph/) platform via an automated ETL pipeline.

    ### Pipeline SLA (Data Freshness)
    **Data Update Schedule**: The extraction engine operates on a daily batch schedule. Prices reflect end-of-day reports generated by the DA. This dashboard does not provide live, minute-by-minute market data.

    ### Standard Operating Procedure
    *   **National Market Watch**: Designed for tactical, daily market analysis. Select a specific administrative region and commodity category to identify lowest prevailing market prices and detect regional price variations.
    *   **Historical Trends**: A strategic analysis tool. Filter by date ranges to identify volatility and supply chain pricing trajectories over time.

    ### Developer Signature
    Built as an automated Data Engineering portfolio project. To view the pipeline architecture or source code, please visit:
    *   [GitHub Profile](https://github.com/crylz-z)

    ### Limitation of Liability
    This platform is provided for informational, educational, and portfolio demonstration purposes only. The data is aggregated from public government sources and is provided 'AS IS' without warranties of any kind, either express or implied, regarding accuracy, completeness, or real-time timeliness. The creator of this platform assumes no liability for any financial, trading, procurement, or business decisions made based on this data. Users must independently verify all prices and market conditions prior to conducting commercial transactions.
    """
    )

st.caption(
    "Data Source: [Department of Agriculture - Bantay Presyo](http://www.bantaypresyo.da.gov.ph/) | © 2026 Agri-Price Intelligence Platform"
)


def main():
    st.title("📋 Official Market Bulletin")

    # ---------------------------
    # SIDEBAR: HIERARCHY
    # ---------------------------
    # The Global Date is now handled above pg.run() and stored in session state
    selected_date = st.session_state.get(
        "global_date", datetime.today().strftime("%Y-%m-%d")
    )

    # LOAD DATA (LKGV)
    raw_df = DataEngine.load_data_window(selected_date)

    if raw_df is None or raw_df.empty:
        st.error(
            f"System Offline: Unable to load data window from Silver layer for {selected_date}."
        )
        return

    # COALESCE (The "Squash" Operation)
    # 1. Sort by Date Descending (Newest first)
    raw_df = raw_df.sort_values("extract_dt", ascending=False)

    # 2. Dedup (Keep first/newest)
    # Natural Key: Region + Market + Commodity.
    df = raw_df.drop_duplicates(
        subset=["region_name", "market_name", "commodity"], keep="first"
    ).copy()

    # 3. Calculate Freshness
    target_dt = datetime.strptime(selected_date, "%Y-%m-%d")
    df["days_ago"] = (target_dt - df["extract_dt"]).dt.days
    df["days_ago"] = df["days_ago"].fillna(0).astype(int)

    # LOAD REFERENCE
    geo_df, srp_df = DataEngine.load_reference_data()

    # ==========================================
    # ZONE B: OFFICIAL PRICE BULLETIN (The Hero)
    # ==========================================
    st.subheader(f"📢 National Price Bulletin ({selected_date})")

    # Aggregate Live Data nationally by Category and Commodity
    # We aggregate Price (mean) and Days Ago (max - being conservative)
    bulletin_df = (
        df.groupby(["category", "commodity"])
        .agg(
            {
                "price": "mean",
                "days_ago": "max",  # If one market is stale, we warn? Or 'min' (best case)?
                # Let's use 'max' (Worst Case) to be transparent.
            }
        )
        .reset_index()
    )

    bulletin_df.rename(columns={"price": "Live Avg"}, inplace=True)

    # Merge with SRP (Left Join to keep all live commodities)
    # Ensure join on commodity name
    bulletin_df = bulletin_df.merge(srp_df, on="commodity", how="left")

    # Logic
    def get_status(row):
        live = row["Live Avg"]
        srp = row["srp"]
        if pd.isna(srp):
            return "N/A"
        if live > (srp * 1.10):
            return "High 🔺"
        if live < (srp * 0.90):
            return "Low 📉"
        return "Fair ✅"

    bulletin_df["Status"] = bulletin_df.apply(get_status, axis=1)
    bulletin_df["Diff"] = bulletin_df["Live Avg"] - bulletin_df["srp"]

    # Formatting Helpers
    def format_currency(val):
        return f"₱{val:,.2f}" if pd.notnull(val) else "—"

    def format_diff(val):
        if pd.isna(val):
            return "—"
        return f"{val:+.2f}"

    def format_freshness(days):
        if days == 0:
            return "Today"
        if days == 1:
            return "Yesterday"
        return f"{days} Days Ago"

    bulletin_df["Data As Of"] = bulletin_df["days_ago"].apply(format_freshness)

    # Display Table
    st.dataframe(
        bulletin_df.style.apply(
            lambda x: ["background-color: #ffe6e6" if "High" in v else "" for v in x],
            subset=["Status"],
        )
        .apply(
            lambda x: [
                "color: #e67e22; font-weight: bold" if v > 0 else "color: #2ecc71"
                for v in x
            ],
            subset=["days_ago"],
        )
        .format(
            {"Live Avg": format_currency, "srp": format_currency, "Diff": format_diff}
        ),
        column_order=[
            "category",
            "commodity",
            "srp",
            "Live Avg",
            "Diff",
            "Status",
            "Data As Of",
        ],
        column_config={
            "category": "Category",
            "commodity": "Commodity",
            "srp": "Prevailing Price (SRP)",
            "Live Avg": "Current Avg Price",
            "Diff": "Variance",
            "Data As Of": "Freshness",
        },
        use_container_width=True,
        hide_index=True,
    )


main()
