
import streamlit as st
import sys
import os

# Ensure root is in path for imports
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../")))

from src.dashboard.utils import ui

ui.apply_enterprise_styling()

# ==========================================
# PAGE HEADER
# ==========================================
st.markdown(
    """
    <div style="text-align:center; margin-bottom:1rem;">
        <h1 style="font-size:2rem; font-weight:700; color:#1e3a5f; margin-bottom:0.1rem;">
            Agri-Price Intelligence Platform
        </h1>
        <p style="color:#6B7280; font-size:0.9rem; margin-top:0;">
            Real-time agricultural commodity price monitoring across the Philippines
        </p>
    </div>
    """,
    unsafe_allow_html=True,
)

# ==========================================
# SYSTEM STATUS — 3-column KPI grid
# ==========================================
st.markdown("#### System Status")
c1, c2, c3 = st.columns(3)
with c1:
    with st.container(border=True):
        st.metric("Coverage", "17 Regions", delta=None)
with c2:
    with st.container(border=True):
        st.metric("Pipeline", "Active", delta="Daily Updates", delta_color="normal")
with c3:
    with st.container(border=True):
        st.metric("Commodities", "6 Categories", delta=None)

st.markdown("<div style='margin-top:1rem;'></div>", unsafe_allow_html=True)

# ==========================================
# AVAILABLE MODULES — 2-column portal cards
# ==========================================
st.markdown("#### Available Modules")
m1, m2 = st.columns(2)

with m1:
    with st.container(border=True):
        st.markdown(
            """
            <h4 style="color:#1e3a5f; margin-bottom:0.25rem;">National Market Watch</h4>
            <p style="color:#6B7280; font-size:0.88rem; margin-top:0;">
                Tactical daily price monitoring — identify regional price variations,
                detect potential price gouging, and pinpoint the best-value markets
                for any commodity on any given date.
            </p>
            """,
            unsafe_allow_html=True,
        )

with m2:
    with st.container(border=True):
        st.markdown(
            """
            <h4 style="color:#1e3a5f; margin-bottom:0.25rem;">Historical Trends</h4>
            <p style="color:#6B7280; font-size:0.88rem; margin-top:0;">
                Strategic long-term analysis — track price trajectories over 7, 30,
                or 90-day windows, measure market volatility, and identify the
                historically cheapest day of the week to buy.
            </p>
            """,
            unsafe_allow_html=True,
        )

st.markdown("---")

# ==========================================
# PLATFORM DOCUMENTATION
# ==========================================
with st.expander("Platform Documentation & Terms of Use", expanded=False):
    st.markdown(
        """
    ### Data Attribution & Architecture
    All data is independently extracted from the official [Philippine Department of Agriculture (DA) Bantay Presyo](http://www.bantaypresyo.da.gov.ph/) platform via an automated ETL pipeline.

    ### Pipeline SLA (Data Freshness)
    **Data Update Schedule**: The extraction engine operates on a daily batch schedule. Prices reflect end-of-day reports generated by the DA. This dashboard does not provide live, minute-by-minute market data.

    ### Standard Operating Procedure
    *   **National Market Watch**: Designed for tactical, daily market analysis. Select a specific administrative region and commodity category to identify lowest prevailing market prices and detect regional price variations.
    *   **Historical Trends**: A strategic analysis tool. Filter by date ranges to identify volatility and supply chain pricing trajectories over time.

    ### Developer Signature
    Built as an automated Data Engineering portfolio project. To view the pipeline architecture or source code, please visit:
    *   [GitHub Profile](https://github.com/crylz-z)

    ### Limitation of Liability
    This platform is provided for informational, educational, and portfolio demonstration purposes only. The data is aggregated from public government sources and is provided 'AS IS' without warranties of any kind, either express or implied, regarding accuracy, completeness, or real-time timeliness. The creator of this platform assumes no liability for any financial, trading, procurement, or business decisions made based on this data. Users must independently verify all prices and market conditions prior to conducting commercial transactions.
    """
    )

st.caption(
    "Data Source: [Department of Agriculture - Bantay Presyo](http://www.bantaypresyo.da.gov.ph/) | © 2026 Agri-Price Intelligence Platform"
)
